---

- name: Downloading installer to target.
  ansible.builtin.get_url:
    url: "{{ ibm_java_sdk_installer }}"
    dest: "{{ installer_download_dir.path }}/{{ ibm_java_sdk_installer.split('/')[-1] }}"
    checksum: "sha1:{{ ibm_java_sdk_sha1sums[ibm_java_sdk_installer.split('/')[-1]] }}"
    mode: '0700'
  register: ibmjavainstaller
