---

- name: Copy installer to target.
  ansible.builtin.copy:
    src: '{{ ibm_java_sdk_installer }}'
    dest: "{{ installer_download_dir.path }}"
    checksum: "{{ ibm_java_sdk_sha1sums[ibm_java_sdk_installer.split('/')[-1]] }}"
    mode: '0700'
  register: ibmjavainstaller
